### ISSUE TITLE
Java 7

### ISSUE THREAD

**Issue by reinij** [spatineo/log-anonymiser#1]
The current version requires Java 8, but in some of our server environments we are still using Java 7. Please check if there is any Java 8 specific in the code.

**Comment by sampov2** [comment]
I've made the required code changes, but Java 7 compatibility also required downgrading both Spring and Google Guava. The Java 7 compatible version is available in this branch: https://github.com/spatineo/log-anonymiser/tree/branch-java7

The earlier version of Spring is perfectaly fine and won't likely cause any issues. But we had to go back to a 2016 version of Google Guava as that's the latest version compatible with Java 7. First level private domain (i.e. server1.foobar.co.uk => foobar.co.uk) is done using that library and the TLD database it contains. The database is probably already somewhat outdated and will only get more and more deteriorated over time.

Due to these reasons I won't merge the changes to master. Let's see if there's a wider need for Java 7 compatibility and work from there.
