### ISSUE TITLE
parse X-Forwarded-For

### ISSUE THREAD

**Issue by trffrm** [spatineo/log-anonymiser#2]
it doesn't seem to work with multiple IPs in X-Forwarded-For field, like

`127.0.0.1 "aa.bbb.cc.ddd, ee.ff.ggg.hhh, 127.0.0.1" - [21/May/2018:06:21:01 +0200] "GET http://..."`

only the first occurrence of 127.0.0.1 gets anonymized unnecessarily, "aa.bbb.cc.ddd, ee.ff.ggg.hhh, 127.0.0.1" doesn't

**Comment by sampov2** [comment]
And just as a note: this anonymiser detects IP addresses and anonymises them. By design, it does not do anything to DNS names (which I assume aa.bbb.cc.ddd and ee.ff.ggg.hhh are in your example). Those are not considered as private information. DNS names can point to multiple IP addresses and they change over time and nobody has the authority to say what DNS name was which IP at what time.

**Comment by trffrm** [comment]
although aa.bbb.cc.ddd and ee.ff.ggg.hhh were meant to represent IP addresses in the example it seems to work now with 1.0.2
